### ISSUE TITLE
Update DNG EOF offsets & Mime Type

### ISSUE THREAD

**Issue by thorsted** [digital-preservation/PRONOM_Research#33]
Hello,

PUID:  fmt/438 has a couple signatures which need increased EOF offsets.  I increased the EOF max offset for signature 670 from 4084 to 128000 and it worked well for my samples.
But would be good to make all DNG signatures consistent.

Also the mime type for many are: MIME:  image/tiff, but I think many folks use: image/x-adobe-dng

**Comment by thorsted** [comment]
Updated info on mime types:

[Microsoft](https://learn.microsoft.com/en-us/windows/win32/wic/dng-format-overview) uses image/dng 

[Adobe](https://experienceleague.adobe.com/docs/experience-manager-65/assets/administer/camera-raw.html?lang=en) also uses image/dng in their documentation

Also in the XMP data when a DNG is converted to TIFF for example, the derived action states, "converted from image/dng to image/tiff".

**Comment by kathaurielle** [comment]
Hi Tyler, thanks for this, I can make these changes.  Can I just check though, for all these sigs, would you like me to make these changes?:
-add MIMEtype  image/dng.
- amend the EOF offset for  all, so that it's 128000 bytes.

the sigs in question:
fmt/436	Digital Negative Format (DNG)	1.0	dng
fmt/437	Digital Negative Format (DNG)	1.2	dng
fmt/438	Digital Negative Format (DNG)	1.3	dng
fmt/730	Digital Negative Format (DNG)	1.4	dng
fmt/1841	Digital Negative Format (DNG)	1.5	dng
fmt/1842	Digital Negative Format (DNG)	1.6	dng
fmt/152	Digital Negative Format (DNG)	1.1	dng

Many thanks,

Kathryn

**Comment by thorsted** [comment]
I have only testing this on DNG 1.3 and it works well, if we can get a test signature with all the changes, I can run it against all my samples to be sure there isn't any issues. @Dclipsham might have some suggestions as well.

**Comment by kathaurielle** [comment]
Thanks, will do this, and add a 1.7 ,exactly the same as 1.6, but with the different signature.

**Comment by tnafrancesca** [comment]
I still need to update all the MIME types but the signatures have been updated if you wish to test your samples on the most recent DevTest upload

**Comment by thorsted** [comment]
@tnafrancesca Looks like the DNG 1.7 signature needs the same priority over fmt/353 as the others.

Thanks.

**Comment by tnafrancesca** [comment]
I'm sorry- you're right, I increased them to 28000 by accident. I will upload a new signature to test in the next few hours!

**Comment by tnafrancesca** [comment]
@thorsted I updated the signature and uploaded a new one. Quick question but did you intend image/dng to be a replacement to the current MIME type or in addition to?

**Comment by thorsted** [comment]
I felt the image/tiff mime was misleading, but I don't use them as much as others do. I'm fine with adding them in addition to if others are expecting it to be there.

**Comment by tnafrancesca** [comment]
These has been included in v.115/v.116 release to be announced shortly
