### ISSUE TITLE
Draw.io Diagram File

### ISSUE THREAD

**Issue by sbshep** [digital-preservation/PRONOM_Research#52]
Note: I submitted this last year via email but I'm not sure if it went through. 

**Format name**
Draw.io Diagram File

**Version number**
n/a

**PUID**
n/a

**Extensions** 
.drawio

**MIME/Media Type**
text/plain

**Description**
A diagramming format used by draw.io, also known as app.diagrams.net. 

**Vendor**
jgraph

**References**
https://github.com/jgraph/drawio
https://app.diagrams.net/
https://www.drawio.com/ 

**File format identification signatures**
Signature(s): 3C6D7866696C65 (see attached XML)
Signature description(s): BOF: offset 0 “<mxfile”
Samples for testing the signature: https://github.com/jgraph/drawio-diagrams/tree/dev/examples

[Draw.io-Diagram-File--signature-file_v1.xml.zip](https://github.com/digital-preservation/PRONOM_Research/files/15000470/Draw.io-Diagram-File--signature-file_v1.xml.zip)

**Credit**
The Church of Jesus Christ of Latter-day Saints

**Comment by tnafrancesca** [comment]
Hello,
Thank you for submitting this issue. We have actually put this in our next release (v.117) which is due to be released in the next couple of weeks. To see the other items that are prepared for the next release here is a link to the spreadsheet- https://docs.google.com/spreadsheets/d/1P1GGevHysUQnivsmf6EFo8ZyfKRPwUJa5eoJ3JODRq0/edit?usp=sharing. I also wanted to thank you as there are a couple of submissions from you in this release as well as a lot of description updates as part of the descriptathon. Thank you for all the hard work that you have put in.

**Comment by sbshep** [comment]
Hi, thanks for reaching out. I couldn't find reference to some of these in my emails and didn't want to forget about them. And I wasn't sure where to check for upcoming releases, so thank you for the link.
