### ISSUE TITLE
New QuarkXPress versions

### ISSUE THREAD

**Issue by thorsted** [digital-preservation/PRONOM_Research#54]
The last QuarkXPress version added was [version 2021](http://www.nationalarchives.gov.uk/PRONOM/fmt/1495). There are three new versions since then. Can we add:

• QuarkXPress 18 | .QXP | 2022 | 0x52
• QuarkXPress 19 | .QXP | 2023 | 0x53
• QuarkXPress 20 | .QXP | 2024 | 0x54

For reference [http://fileformats.archiveteam.org/wiki/Quark_Xpress](http://fileformats.archiveteam.org/wiki/Quark_Xpress)

**Comment by tnafrancesca** [comment]
These will be in the next release, looking at the way that QuarkXPress versioning has been done in PRONOM (combination of year of release and version number) I am thinking of making all QuarkXPress project files only have the version number (perhaps with an alias). Would you have any objection to this plan?

**Comment by richardlehane** [comment]
I've just been testing v119 and there seems to be an issue with these new QuarkXPress signatures. A whole lot of QuarkXPress files are now matching Project 19 ([fmt/2007](https://www.nationalarchives.gov.uk/PRONOM/fmt/2007)). 

The issue seems to be that the new signatures for fmt/2007 are generic and missing the version information.

![image](https://github.com/user-attachments/assets/df574389-6d6f-4ec4-ad5c-4649eb0cda89)

**Comment by tnafrancesca** [comment]
Thank you everyone for raising this issue- it will be resolved in the next release (late September/ early October) and in the next couple of weeks I'll be creating a test signature to make sure that it is resolved.
